### ISSUE TITLE
Include CLI interface for SOL to JSON conversion

### ISSUE THREAD

**Issue by AndreaFilippi** [gmariani/minerva#104]
It would be a great thing to include a simple Command Line Interface to use .minerva as .sol to .json converter.
i.e.
 >minerva.exe -sol<file.sol> -o<file.json>
i am using 3.6.0 air version, great tool!

**Comment by gmariani** [comment]
The adobe AIR version has been discontinued, So only the web browser version exists. So unfortunately there will not be a CLI version anytime soon.
