### ISSUE TITLE
[Request] Offline Editor Tool

### ISSUE THREAD

**Issue by RedAISkye** [gmariani/minerva#105]
I'd prefer if the editor was an offline tool instead that doesn't require you to use browser or internet.

Is it possible please?

**Comment by gmariani** [comment]
Anything can be programmed; but what I'm willing to do, no it will remain online only. It does allow you to go offline once you've loaded it once though.

**Comment by RedAISkye** [comment]
> Anything can be programmed; but what I'm willing to do, no it will remain online only. It does allow you to go offline once you've loaded it once though.

Is it possible to at least save the page so, it still works offline even if you exit the browser and revisit later?

**Comment by gmariani** [comment]
It should already do that. It does have an offline mode, it's had one for a few years i believe. Although I haven't tried in a long time to see if it still works.

**Comment by RedAISkye** [comment]
> It should already do that. It does have an offline mode, it's had one for a few years i believe. Although I haven't tried in a long time to see if it still works.

Nope, it's not working. Tried saving as a single HTML file and its all broken so tried saving via SingleFile addon and it seems to have only saved the design and not the scripts so the buttons do nothing.

Finally, tried saving as complete webpage and it loads fine but when I tried to load the save, I get an error both online/offline saying the following:-

```
Error

Error reading file:
undefined
(undefined:undefined)
```

So, I'm assuming not all scripts are saved :\

**Comment by gmariani** [comment]
no, there is nothing to save. you just use the website as normal when you're offline. Saving it is going to break it.
