### ISSUE TITLE
About the local version

### ISSUE THREAD

**Issue by NPC0123** [gmariani/minerva#108]
Friend, I hope you can create a local version that can be downloaded and used directly. 
Configuring the server and compiling the code is not very clear and convenient.

**Comment by gmariani** [comment]
You can use it offline. You don't need to install anything. So in a sense, you already can "download" it and use it directly.

**Comment by NPC0123** [comment]
I tried downloading and using (found minerva/app/index. html), and the webpage was loaded. I was able to load Sol, but it couldn't be parsed.
Perhaps there is a problem with my usage, please tell me the correct one.

**Comment by NPC0123** [comment]
> 可以离线使用。你不需要安装任何东西。所以在某种意义上，你已经可以“下载”并直接使用它了。

I tried downloading and using (found minerva/app/index. html), and the webpage was loaded. I was able to load Sol, but it couldn't be parsed.
Perhaps there is a problem with my usage, please tell me the correct one.

**Comment by NPC0123** [comment]
> You can use it offline. You don't need to install anything. So in a sense, you already can "download" it and use it directly.

I tried downloading and using (found minerva/app/index. html), and the webpage was loaded. I was able to load Sol, but it couldn't be parsed.
Perhaps there is a problem with my usage, please tell me the correct one.

**Comment by gmariani** [comment]
You just visit the website https://mariani.life/projects/minerva/ , that's it. Once you visit it once, it'll cache in your browser and you can go offline with it. No need to download or install anything.

**Comment by NPC0123** [comment]
> You just visit the website https://mariani.life/projects/minerva/ , that's it. Once you visit it once, it'll cache in your browser and you can go offline with it. No need to download or install anything.

Okay, thank you, my friend.
I'm just afraid that one day you'll shut down this website, after all, I've seen too many such situations before
