### ISSUE TITLE
Unable to open sol file in Firefox (43.0.4) when offline

### ISSUE THREAD

**Issue by HarelMym** [gmariani/minerva#63]
Using .minerva in Firefox, .sol files open properly when online, but when in offline mode or not connected to internet, .minerva reports:

"Error reading file:
: NS_ERROR_FAILURE:
(http://apps.coursevector.com/minerva/js/parsers/SOLReaderWorker.js:1)"

and fails to parse the file.

[edit] IE 11 and Chrome 47 each produce the same error regarding SOLReaderWorker.js when not online [/edit]

**Comment by gmariani** [comment]
This has been fixed in 4.2.0

**Comment by gmariani** [comment]
4.2.0 is now live
