### ISSUE TITLE
Serialization object, how to see its content

### ISSUE THREAD

**Issue by Tudumanu** [gmariani/minerva#68]
I am opening the .sol files from a game called Auro, the file only show me this:
```
Cy41:serialization.progress.AuroProgressObjectfznnnzzzi7ny0:fni-1znR1g
```
![tmpsol](https://cloud.githubusercontent.com/assets/5518496/24482044/e6d4b7f2-14c4-11e7-89ef-eaeda54f4063.PNG)

Any idea on how it was saved and how to see more of the object contents?

**Comment by gmariani** [comment]
Can you attach the file you're testing?

**Comment by Tudumanu** [comment]
yes, see attached


[Auro.sol.zip](https://github.com/gmariani/cv-minerva/files/883480/Auro.sol.zip)

**Comment by gmariani** [comment]
Unfortunately that looks they used a serialized object. Which means they have it custom write the object in the SOL. There is no way for .minerva to parse that object since it can't assume how the object is written. Sorry, can't fix this. It's working as intended.
