### ISSUE TITLE
seems to have corrupted the file...

### ISSUE THREAD

**Issue by Brian151** [gmariani/minerva#71]
the one with "-test" suffix both completely failed to parse on minerva (version ???, and it just says parsing, but obviously failed, as the original opens in less than a second), and doesn't seem to be correctly recognized by flash player, either. I lost a save because of this. Really not too happy about that, either, since the particular game is a pain, and already has serious glitches....

[SBLK-sols.zip](https://github.com/gmariani/cv-minerva/files/1332219/SBLK-sols.zip)

**Comment by gmariani** [comment]
Console reports:

    main.min.js:228 Uncaught TypeError: Cannot read property 'value' of null
        at a (main.min.js:228)
        at b (main.min.js:231)
        at a (main.min.js:229)
        at b (main.min.js:231)
        at a (main.min.js:229)
        at b (main.min.js:231)
        at SOL.obj2Tree (main.min.js:236)
        at Worker.e.onmessage (main.min.js:237)
    a @ main.min.js:228
    b @ main.min.js:231
    a @ main.min.js:229
    b @ main.min.js:231
    a @ main.min.js:229
    b @ main.min.js:231
    SOL.obj2Tree @ main.min.js:236
    e.onmessage @ main.min.js:237

**Comment by Brian151** [comment]
Will check this again soon!
thx

**Comment by gmariani** [comment]
4.2.0 is now live. Be sure to clear your browser cache a few times just to be sure nothing is lingering from the old one as I completely changed how it loads.

**Comment by Brian151** [comment]
i havn't yet tried it again on the files in question, but it did help me hacking the saves of a few games that were particularly annoying to play (one used a custom format, it looks like...)
