### ISSUE TITLE
Saving error

### ISSUE THREAD

**Issue by leviathan13** [gmariani/minerva#78]
> Error saving file:
> Uncaught RangeError: Too many elements in SOL file to process in your current browser.
> (https://mariani.life/projects/minerva/js/parsers/SOLWriterWorker.js:1)

Is this an error that could be avoided? I just tried to edit a savegame file.

**Comment by gmariani** [comment]
Can you attach the save file? When minerva parses the file, it creates a version in memory many times the size because it describes every part of it. So if there is an array with 1000 items, it may be 10 times that size in memory and exhaust the memory stack. But without seeing the save file it's hard to tell.

**Comment by leviathan13** [comment]
I'm trying to edit the save file of [Infectonator: Survivors](https://store.steampowered.com/app/269310/Infectonator_Survivors/). This is an example of the game's [save file](http://www.filedropper.com/infectonatorsurvivors76561198009932603).

Is it because it's an online tool? Is there an offline version?

**Comment by gmariani** [comment]
Added file from filedropper
[InfectonatorSurvivors76561198009932603.sol.txt](https://github.com/gmariani/minerva/files/2109554/InfectonatorSurvivors76561198009932603.sol.txt)

**Comment by gmariani** [comment]
Looks like it's having trouble reading in some strings and then when it goes to save, it does it incorrectly.
Open the file and look at savedObjectData->carRepairsArray->0
That error means it didn't read in the string reference properly for whatever reason. I'll check this out.

**Comment by gmariani** [comment]
Was this file previously edited with minerva or was this straight from the game?

**Comment by gmariani** [comment]
Ok, i got this fixed. it was an object reference error. It's been pushed to 4.3.1
