### ISSUE TITLE
i would like to download this to the pc so i dont need to keep a tab open 24/7

### ISSUE THREAD

**Issue by harbinger942** [gmariani/minerva#80]

**Comment by gmariani** [comment]
I don't know why you would keep the tab open 24/7... What are you doing?
I am looking into making this a PWA so you can have a shortcut directly to the app from your desktop. But still, why would you leave it open?

**Comment by gmariani** [comment]
I made it modern PWA, so if you enable experimental flags in Chrome you can run it like an app: https://www.xda-developers.com/progressive-web-apps-chrome-how-to/
