### ISSUE TITLE
Error opening boolian 

### ISSUE THREAD

**Issue by Colonizor48** [gmariani/minerva#83]
when i import Json it imports fine but wont save it retuns Uncaught Error: Undefined AMF3 type encountered 'Boolean'
(https://cdn.mariani.life/projects/minerva/js/lib/AMF3.js:1)

**Comment by gmariani** [comment]
Do you have a sample file for me to test with?

**Comment by Colonizor48** [comment]
try importing htis {"credits":683,"tasks":["TaskGamma"],"shipParts":[["BigCore1", 0, 0, 0, false], ["BigSide1", 9, -11, 180, false], ["BigSide1", -9, -11, 180, true], ["MediumCenter3", 0, -13, 180, false], ["BigWing1", -20, 22, 0, false], ["BigSide2", -13, 19, 180, true], ["BigWing1", 20, 22, 0, true], ["BigSide2", 13, 19, 180, false], ["BigWing1", 10, 27, 0, true], ["BigWing1", -10, 27, 0, false], ["BigSide4", -15, 12, 90, false], ["BigSide4", 15, 12, 270, true], ["BigSide1", -12, 5, 90, true], ["BigSide1", 12, 5, 270, false], ["BigSide3", -13, -1, -90, true], ["BigSide3", 13, -1, 90, false], ["BigSide1", -7, 17, 180, false], ["BigSide1", 7, 17, 180, true], ["BigCenter2", 0, -6, 0, false], ["BigCenter2", 0, 6, 0, false]], [["ProjArcade"], ["EnergyReg3"], ["EnergyReg3"], ["EngineAcc2"], ["Beam3"], ["EnergyReg3"], ["EngineMax3"], ["Projectile3"], ["SpeedThrust3"], ["ShellBoost3"], ["Disrupt3"], ["Beam3"], ["Cannon3"], ["Missile3"], ["RegenThrust3"], ["ShellBoost3"]],"Ship","Player","PLAYER","AirUnit"],"completedTasks":["Task1","TaskPart","Task2","Task3","TaskRescue","MoveToHaven2","TaskAlpha","TaskBeta","TaskSide0"],"password":"e","knownSectors":["Haven4","Dead70_50","Haven1","Sector25_25","Dead0_25","Dead0_50","Sector70_25","Dead0_0","Dead0_0","Start","Start","Dead100_0","Dead100_0","Haven2","Haven2","Alpha","Alpha","Sector140_25","Sector140_25","Beta","Beta","Sector175_50","Sector175_50","Sector100_90","Sector100_90","Gamma","Gamma"],"shards":[],"score":937,"yardParts":[[],[],"Ship","Player","PLAYER"],"homeSector":"Haven2"} and saving it

**Comment by Colonizor48** [comment]
if there are any bugs in it fix them
imean th ejson

**Comment by Colonizor48** [comment]
h

**Comment by gmariani** [comment]
This is fixed in v4.3.3 which will be out in a day or so
