### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LBXMaster** [gmariani/minerva#84]
Error reading file:
Uncaught
(https://mariani.life/projects/minerva/js/parsers/SOLReaderWorker.js:1)

i don't know what happen but sometimes Minerva opens differently and when i opened the webpage complete version, this happened

**Comment by gmariani** [comment]
that's kinda vague. how do i reproduce the error?

**Comment by LBXMaster** [comment]
Basically go to the minerva site and try to open a shockwave file. That is
all for me to met that error

**Comment by LBXMaster** [comment]
Tried it again in anothe computer, same result

**Comment by gmariani** [comment]
Yeah, this is not enough for me to do anything with. I have no problems opening the file. If you're thinking Shockwave is the same as Flash you would be incorrect. That might be your issue.
