### ISSUE TITLE
Site broken

### ISSUE THREAD

**Issue by zeBaconcake** [gmariani/minerva#87]
I tried in several browsers and devices, the site is broken, nothing works and the certificate ran out almost 20 days ago

**Comment by gmariani** [comment]
I'm well aware of the issue. I'm working with cPanel to resolve it. Seems they have a bug with their AutoSSL that isn't allowing me to add the proper CAA record to allow letsencrypt to renew.

**Comment by gmariani** [comment]
it's fixed
