### ISSUE TITLE
compiled version not available for download? (AIR)

### ISSUE THREAD

**Issue by eksynn** [gmariani/minerva#90]
i downloaded the latest source code (4.3.4), but i have no idea how to compile it. and the website version is extremely outdated.
could we also have a compiled version available for download in the latest release, please?

**Comment by gmariani** [comment]
Can you explain what you mean?
"i downloaded the latest source code (4.3.4), but i have no idea how to compile it." - you don't need to, you just visit the website. The latest version if 4.3.5 https://mariani.life/projects/minerva/ . But even if you are talking about the AIR version, I did post an updated (resigned) link to 3.5.0 on there that you can still download.

"and the website version is extremely outdated." - Not sure which website you're talking about, https://mariani.life/projects/minerva-air/ is for the AIR version which was discontinued. https://mariani.life/projects/minerva/ is for the web version which replaced it.

"could we also have a compiled version available for download in the latest release, please?" - Can you be more specific which version you're talking about? All the latest versions are accessible and/or downloadable as applicable.

**Comment by gmariani** [comment]
I see what you mean about the "release" on github only being 4.3.4. That makes sense there, I use github to track the source code and issues. I don't really use it for releases which is probably why it slipped my mind. Again, it's meant to be used via the website primarily.

**Comment by gmariani** [comment]
updated the latest release

**Comment by eksynn** [comment]
> Can you explain what you mean?
sure, i'll do my best ^^

> "i downloaded the latest source code (4.3.4), but i have no idea how to compile it." - you don't need to, you just visit the website. The latest version is 4.3.5 https://mariani.life/projects/minerva/ . But even if you are talking about the AIR version, I did post an updated (resigned) link to 3.5.0 on there that you can still download.
> 
> "and the website version is extremely outdated." - Not sure which website you're talking about, https://mariani.life/projects/minerva-air/ is for the AIR version which was discontinued. https://mariani.life/projects/minerva/ is for the web version which replaced it and is up to date.
oh. yea that's the one i meant lol
i see, i wasn't aware that the air version was retired - that's the one i knew about a few years ago, when i used minerva. is there any chance for the air version to be updated, or should i download 3.5.0? (i'm not always online, so using a browser-only tool can be more hindering than useful to me - and minerva is an extremely useful tool to me)

> "could we also have a compiled version available for download in the latest release, please?" - Can you be more specific which version you're talking about? All the latest versions are accessible and/or downloadable as applicable.
i think i was referring to the AIR version

**Comment by gmariani** [comment]
I do not plan on updating the AIR version at this point. Flash is dead and not really worth it at this point. As for the browser version, it is built to work off-line so you SHOULD be able to use it without internet once you visit the site once. It uses service-workers and site caching and other nonsense to kind of work like an app. It doesn't rely on my server for anything other than to load once so give it a try and see if that works for you.

**Comment by eksynn** [comment]
> I do not plan on updating the AIR version at this point. Flash is dead and not really worth it at this point. As for the browser version, it is built to work off-line so you SHOULD be able to use it without internet once you visit the site once. It uses service-workers and site caching and other nonsense to kind of work like an app. It doesn't rely on my server for anything other than to load once so give it a try and see if that works for you.

it also seems to work if i just plainly download the site lol (ctrl+s)
i can just launch the html file it generates and it seems to work. but is the website updated to the latest version? (4.3.5 i think it was?)
thank you for making it work that way! (but since it's offline, there are no ads. may i remove the ad space? it's distracting lol - also, how, without breaking everything?)

**Comment by gmariani** [comment]
Yes you can remove the ad-space, i will leave that to you to figure out. =)
And yes, the website should be the latest version.
