### ISSUE TITLE
Problem found while using Minerva in Chrome Ver.86.0.4240

### ISSUE THREAD

**Issue by LBXMaster** [gmariani/minerva#92]
**It appears your browser does not support:

Application Cache API - Used to take the application offline
Please upgrade your browser in order to use .minerva.**

I don't know what happened but the error in bold happened when I want to use MInerva after a long while of not using it.
Tried it on 2 laptops, same problem happened

**Comment by elvisjr444** [comment]
a mi me sale igual por favor ayudaaaaaaaaaaaa

**Comment by gmariani** [comment]
Chrome dropped the feature in v85, and I don't think minerva even uses it any more. removed the warning.

**Comment by gmariani** [comment]
this is a duplicate of https://github.com/gmariani/minerva/issues/91
