### ISSUE TITLE
Custom class incorrectly decoded as Date object

### ISSUE THREAD

**Issue by henke37** [gmariani/minerva#94]
Custom classes registered with the `registerClassAlias` method are incorrectly decoded as `Date` objects.
[saveList.zip](https://github.com/gmariani/minerva/files/5823696/saveList.zip)

**Comment by Zaseth** [comment]
Hey there. Could you try running this data through readObject in my library called [ByteArray](https://github.com/Zaseth/bytearray-node)

**Comment by henke37** [comment]
That's going to be rather problematic, since I've never used node.js.

**Comment by gmariani** [comment]
this seems to be working again in 4.3.6

**Comment by henke37** [comment]
Can confirm, works for me now
